name: Code quality

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
    
  pull_request:
    types: [opened, reopened]
    paths:
      - "aws_lambda_powertools/**"
      - "tests/e2e/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "mypy.ini"
      - "parallel_run_e2e.py"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    env:
      PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_APIKEY }}
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: make dev
      - name: Test with pytest
        run: make test
      - name: echo coverage
        shell: bash
        run: |
          cat ./coverage.xml
      - name: Analyze Test and/or Coverage Results
        uses: runforesight/foresight-test-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_APIKEY }}
          test_format: JUNIT
          test_framework: PYTEST
          test_path: ./results/**
          coverage_path: ./coverage.xml
          coverage_format: COBERTURA/XML
